import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
//Deodorant

export const products = [
  {
    _id: uuid(),
    productName: "Jannatul Firdaus ",
    productDescription:
      "Jannatul Firdaus Concentrated Perfume Free From Alcohol 10ml For Unisex",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/Jannatul-Firadus1.png?v=1638013417",
    categoryName: "Contcentrated Perfumes",
    price: 500,
    discountPercent: 10,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Global Desi Rhythmic",
    productDescription: "Soul Body Mist 200ML For Women Crafted By Ajmal",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/RhythmicSoul1.jpg?v=1665654223",
    categoryName: "Body Mist",
    price: 2520,
    discountPercent: 5,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Ascend Deodorant",
    productDescription: "Oriental Perfume 150ML For Unisex",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/ASCEND_DEODORANT_150ML_1.jpg?v=1668515844",
    categoryName: "Deodorant ",
    price: 250,
    discountPercent: 20,
    discountedPrice: 50,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Dakhoon ",
    productDescription: "Dakhoon Al Safa 200GMS",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/DakhoonAlsafa-2.jpg?v=1637739757",
    categoryName: "Home Fragrances",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Kouros Body Cologne",
    productDescription: "100 ml Eau De Toilette Spray",
    productImage:
      "https://img.fragrancex.com/images/products/parent/medium/777m.webp",
    categoryName: "Body Mist",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Jimmy Choo Man",
    productDescription:
      "Jimmy Choo Man Blue Cologne 100 ml Eau De Toilette Spray",
    productImage:
      "https://img.fragrancex.com/images/products/parent/medium/76480m.webp",
    categoryName: "Contcentrated Perfumes",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Crystal Noir Perfume",
    productDescription: "90 ml Eau De Parfum Spray",
    productImage:
      "https://img.fragrancex.com/images/products/parent/medium/60546w.webp",
    categoryName: "Contcentrated Perfumes",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "AND Serene Bliss Body Mist ",
    productDescription:
      "AND Serene Bliss Body Mist 200ML For Women Crafted By Ajmal",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/SereneBliss1.jpg?v=1665654754",
    categoryName: "Body Mist",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Carbon Deodorant ",
    productDescription: "Carbon Perfume Deodorant 200ml For Men",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/Carbon1_c02c5069-27a3-4a37-bf1b-5d9ca0482229.jpg?v=1637739391",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Arcelia",
    productDescription: "Mens Deo Chivalorus Charm 150 ml",
    productImage:
      "https://sslimages.shoppersstop.com/sys-master/images/he1/hac/28466727583774/A21DEOCC150ML-M_NoColour.jpg_2000Wx3000H",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Beverly Hills Polo Club",
    productDescription: "Sports Men Nine Deo 175ml",
    productImage:
      "https://sslimages.shoppersstop.com/sys-master/images/heb/h2f/14750573953054/206926333_9999.jpg_2000Wx3000H",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "",
    productDescription: "",
    productImage:
      "",
    categoryName: "Deodorant",
    price: 0,
    discountPercent: 0,
    discountedPrice: 110,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
];
