//import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
//Deodorant

export const products = [
  {
    id: 1,
    productName: "Jannatul Firdaus ",
    productDescription:
      "Jannatul Firdaus Concentrated Perfume Free From Alcohol 10ml For Unisex",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/Jannatul-Firadus1.png?v=1638013417",
    categoryName: "Contcentrated Perfumes",
    price: 400,
    discountPercent: 50,
    orignalPrice: 800,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 2,
    productName: "Global Desi Rhythmic",
    productDescription: "Soul Body Mist 200ML For Women Crafted By Ajmal",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/RhythmicSoul1.jpg?v=1665654223",
    categoryName: "Body Mist",
    price: 450,
    discountPercent: 50,
    orignalPrice: 900,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 3,
    productName: "Ascend Deodorant",
    productDescription: "Oriental Perfume 150ML For Unisex",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/ASCEND_DEODORANT_150ML_1.jpg?v=1668515844",
    categoryName: "Deodorant ",
    price: 240,
    discountPercent: 20,
    orignalPrice: 300,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 4,
    productName: "Dakhoon ",
    productDescription: "Dakhoon Al Safa 200GMS",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/DakhoonAlsafa-2.jpg?v=1637739757",
    categoryName: "Home Fragrances",
    price: 450,
    discountPercent: 10,
    orignalPrice: 500,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 5,
    productName: "Kouros Body Cologne",
    productDescription: "100 ml Eau De Toilette Spray",
    productImage:
      "https://img.fragrancex.com/images/products/parent/medium/777m.webp",
    categoryName: "Body Mist",
    price: 480,
    discountPercent: 20,
    orignalPrice: 600,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 6,
    productName: "Jimmy Choo Man",
    productDescription:
      "Jimmy Choo Man Blue Cologne 100 ml Eau De Toilette Spray",
    productImage:
      "https://img.fragrancex.com/images/products/parent/medium/76480m.webp",
    categoryName: "Contcentrated Perfumes",
    price: 810,
    discountPercent: 10,
    orignalPrice: 900,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 7,
    productName: "Crystal Noir Perfume",
    productDescription: "90 ml Eau De Parfum Spray",
    productImage:
      "https://img.fragrancex.com/images/products/parent/medium/60546w.webp",
    categoryName: "Contcentrated Perfumes",
    price: 1188,
    discountPercent: 5,
    orignalPrice: 1250,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 8,
    productName: "AND Serene Bliss Body Mist ",
    productDescription:
      "AND Serene Bliss Body Mist 200ML For Women Crafted By Ajmal",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/SereneBliss1.jpg?v=1665654754",
    categoryName: "Body Mist",
    price: 200,
    discountPercent: 0,
    orignalPrice: 200,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 9,
    productName: "Carbon Deodorant ",
    productDescription: "Carbon Perfume Deodorant 200ml For Men",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/Carbon1_c02c5069-27a3-4a37-bf1b-5d9ca0482229.jpg?v=1637739391",
    categoryName: "Deodorant",
    price: 171,
    discountPercent: 5,
    orignalPrice: 180,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 10,
    productName: "Bleu de Chanel ",
    productDescription: "Mens Deo Chivalorus Charm 150 ml",
    productImage:
      "https://cdn.shopify.com/s/files/1/0305/1601/9337/products/bdcedp_75996243-d5da-4fb3-8a18-906ded11e4fd_1024x1024.jpg?v=1579033588",
    categoryName: "Body Mist",
    price: 208,
    discountPercent: 20,
    orignalPrice: 260,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 11,
    productName: "Lady Million",
    productDescription:
      "Paco Rabanne Bitter orange Heart Notes Orange blossom,Jasmine sambac ",
    productImage:
      "https://cdn.shopify.com/s/files/1/0305/1601/9337/products/375x500.9045_1024x1024.jpg?v=1579629483",
    categoryName: "Body Mist",
    price: 4000,
    discountPercent: 20,
    orignalPrice: 5000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 12,
    productName: "Pure Posion",
    productDescription: "Dior Pure Poison Eau de Parfum",
    productImage:
      "https://cdn.shopify.com/s/files/1/0305/1601/9337/products/pure_poison_1024x1024.jpg?v=1581864402",
    categoryName: "Body Mist",
    price: 7600,
    discountPercent: 5,
    orignalPrice: 8000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 13,
    productName: "Gucci Bloom",
    productDescription:
      "Jasmine and Honeysuckle; middle note is Tuberose; base notes are Damask Rose and Orris.",
    productImage:
      "https://cdn.shopify.com/s/files/1/0305/1601/9337/products/132644_img-2196-gucci-bloom-ambrosia-di-fiori_720_1024x1024.jpg?v=1650794859",
    categoryName: "Deodorant",
    price: 4500,
    discountPercent: 10,
    orignalPrice: 5000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 14,
    productName: "Jaguar Classic ",
    productDescription: "Jaguar Classic Chromite Eau de Toilette (100ml)",
    productImage:
      "https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/jaguar/952671/0/WjVToRZiKA-s8Yl8f3Iv8-1.png?dpr=1",
    categoryName: "Deodorant",
    price: 10800,
    discountPercent: 10,
    orignalPrice: 12000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 15,
    productName: "Jean Paul Gaultier",
    productDescription: "Jean Paul Gaultier So Scandal! Eau De Parfum (30ml)",
    productImage:
      "https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1049798/-Lue6G8xVt-1049798_1.jpg?dpr=1",
    categoryName: "Contcentrated Perfumes",
    price: 8100,
    discountPercent: 10,
    orignalPrice: 9000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 16,
    productName: "Rabanne Olympea",
    productDescription: "Paco Rabanne Olympea Solar Eau de Parfum (30ml)",
    productImage:
      "https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/1049713/O4gsHy0HGt-3349668599424_1.jpg?dpr=1",
    categoryName: "Contcentrated Perfumes",
    price: 2800,
    discountPercent: 20,
    orignalPrice: 3500,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 17,
    productName: "Missoni Perfumed ",
    productDescription: "Missoni Perfumed Deodorant (50ml) ",
    productImage:
      "https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/missoni/1066826/0/ke3HghDRY7-aHiCFP5-N-8011003832835_1.jpg?dpr=1",
    categoryName: "Deodorant",
    price: 1900,
    discountPercent: 5,
    orignalPrice: 2000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 18,
    productName: "Jaguar Classic ",
    productDescription: "Jaguar Classic Chromite Eau de Toilette (100ml)",
    productImage:
      "https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/original/jaguar/952671/0/WjVToRZiKA-s8Yl8f3Iv8-1.png?dpr=1",
    categoryName: "Deodorant",
    price: 10800,
    discountPercent: 10,
    orignalPrice: 12000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 19,
    productName: "Gucci Bloom",
    productDescription:
      "Jasmine and Honeysuckle; middle note is Tuberose; base notes are Damask Rose and Orris.",
    productImage:
      "https://cdn.shopify.com/s/files/1/0305/1601/9337/products/132644_img-2196-gucci-bloom-ambrosia-di-fiori_720_1024x1024.jpg?v=1650794859",
    categoryName: "Deodorant",
    price: 4500,
    discountPercent: 10,
    orignalPrice: 5000,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    id: 20,
    productName: "Carbon Deodorant ",
    productDescription: "Carbon Perfume Deodorant 200ml For Men",
    productImage:
      "https://in.ajmalperfume.com/cdn/shop/products/Carbon1_c02c5069-27a3-4a37-bf1b-5d9ca0482229.jpg?v=1637739391",
    categoryName: "Deodorant",
    price: 171,
    discountPercent: 5,
    orignalPrice: 180,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
];
